# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56a74ca4db92f679756ae81ae8e2fe15978ad11cbb9e31a4cf2e8e9bda60fe610346946475e365b6b6e9508e62ec0f4d4c3b90cc7a04d6443b59911b224d04c2

test:
  secret_key_base: ddf73a045d17babcc216624b4640b559f939dcaeb8b3a0d000076b8456ab107be0b42879e4347081c67591c7025d1d8e31a822b1b6262a89ec6146479cca678f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
