# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c8b6548601fef3e69c98ab7d55d6ca4c7eb63d3441e3b1094638879f942491772f8cc18c94d90f93f62832fb1b810020ac8bb04acc959ff7fb0d322e7bac7e6

test:
  secret_key_base: a22b1eee3e44e1b02f761fb2abf5c73a108b7cff29f6d6439d09c963b21eacc42d3e7d4bf11b7331f02221aaca3f581814716cb6601269e75e202c419523fcbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
